preload = /home/asher/Pictures/Wallpapers/spider-verse.png
preload = /home/asher/Pictures/Wallpapers/spider-verse-portrait-og.jpg

wallpaper = DP-1, /home/asher/Pictures/Wallpapers/spider-verse-portrait-og.jpg
wallpaper = HDMI-A-1, /home/asher/Pictures/Wallpapers/spider-verse.png
